# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_formrsachat(object):
    def setupUi(self, formrsachat):
        formrsachat.setObjectName("formrsachat")
        formrsachat.resize(640, 510)
        formrsachat.setMinimumSize(QtCore.QSize(640, 510))
        formrsachat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget = QtWidgets.QTabWidget(formrsachat)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 625, 441))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setEnabled(True)
        self.tab.setObjectName("tab")
        self.lineEditSendMsg = QtWidgets.QPlainTextEdit(self.tab)
        self.lineEditSendMsg.setGeometry(QtCore.QRect(5, 353, 475, 50))
        self.lineEditSendMsg.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lineEditSendMsg.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lineEditSendMsg.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lineEditSendMsg.setObjectName("lineEditSendMsg")
        self.pushButtonCreateRoom = QtWidgets.QPushButton(self.tab)
        self.pushButtonCreateRoom.setEnabled(False)
        self.pushButtonCreateRoom.setGeometry(QtCore.QRect(487, 295, 123, 20))
        self.pushButtonCreateRoom.setMinimumSize(QtCore.QSize(123, 0))
        self.pushButtonCreateRoom.setMaximumSize(QtCore.QSize(123, 20))
        self.pushButtonCreateRoom.setObjectName("pushButtonCreateRoom")
        self.lineEditNameNewRoom = QtWidgets.QLineEdit(self.tab)
        self.lineEditNameNewRoom.setEnabled(True)
        self.lineEditNameNewRoom.setGeometry(QtCore.QRect(487, 269, 123, 20))
        self.lineEditNameNewRoom.setMinimumSize(QtCore.QSize(123, 0))
        self.lineEditNameNewRoom.setMaximumSize(QtCore.QSize(123, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEditNameNewRoom.setFont(font)
        self.lineEditNameNewRoom.setMaxLength(30)
        self.lineEditNameNewRoom.setObjectName("lineEditNameNewRoom")
        self.labelOnline = QtWidgets.QLabel(self.tab)
        self.labelOnline.setGeometry(QtCore.QRect(487, 7, 123, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelOnline.setFont(font)
        self.labelOnline.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelOnline.setAutoFillBackground(False)
        self.labelOnline.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelOnline.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOnline.setObjectName("labelOnline")
        self.labelNameRoom = QtWidgets.QLabel(self.tab)
        self.labelNameRoom.setGeometry(QtCore.QRect(5, 7, 475, 20))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.labelNameRoom.setFont(font)
        self.labelNameRoom.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.labelNameRoom.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelNameRoom.setTextFormat(QtCore.Qt.AutoText)
        self.labelNameRoom.setObjectName("labelNameRoom")
        self.pushButtonSendMsg = QtWidgets.QPushButton(self.tab)
        self.pushButtonSendMsg.setEnabled(False)
        self.pushButtonSendMsg.setGeometry(QtCore.QRect(487, 370, 123, 30))
        self.pushButtonSendMsg.setMinimumSize(QtCore.QSize(123, 0))
        self.pushButtonSendMsg.setMaximumSize(QtCore.QSize(123, 16777215))
        self.pushButtonSendMsg.setObjectName("pushButtonSendMsg")
        self.textEditGlobal = QtWidgets.QTextEdit(self.tab)
        self.textEditGlobal.setGeometry(QtCore.QRect(5, 32, 475, 318))
        self.textEditGlobal.setMinimumSize(QtCore.QSize(460, 0))
        self.textEditGlobal.setUndoRedoEnabled(True)
        self.textEditGlobal.setReadOnly(True)
        self.textEditGlobal.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEditGlobal.setObjectName("textEditGlobal")
        self.listWidgetRooms = QtWidgets.QListWidget(self.tab)
        self.listWidgetRooms.setGeometry(QtCore.QRect(487, 32, 123, 231))
        self.listWidgetRooms.setMinimumSize(QtCore.QSize(123, 0))
        self.listWidgetRooms.setMaximumSize(QtCore.QSize(123, 16777215))
        self.listWidgetRooms.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.listWidgetRooms.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidgetRooms.setObjectName("listWidgetRooms")
        self.pushButtonExitRoom = QtWidgets.QPushButton(self.tab)
        self.pushButtonExitRoom.setEnabled(False)
        self.pushButtonExitRoom.setGeometry(QtCore.QRect(487, 320, 123, 20))
        self.pushButtonExitRoom.setMinimumSize(QtCore.QSize(123, 0))
        self.pushButtonExitRoom.setMaximumSize(QtCore.QSize(123, 20))
        self.pushButtonExitRoom.setObjectName("pushButtonExitRoom")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBoxHostPortNick = QtWidgets.QGroupBox(self.tab_2)
        self.groupBoxHostPortNick.setEnabled(True)
        self.groupBoxHostPortNick.setGeometry(QtCore.QRect(10, 0, 601, 60))
        self.groupBoxHostPortNick.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBoxHostPortNick.setTitle("")
        self.groupBoxHostPortNick.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxHostPortNick.setFlat(False)
        self.groupBoxHostPortNick.setCheckable(False)
        self.groupBoxHostPortNick.setObjectName("groupBoxHostPortNick")
        self.layoutWidget = QtWidgets.QWidget(self.groupBoxHostPortNick)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 20, 581, 34))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setLineWidth(1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.lineEditPort = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditPort.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEditPort.setMaxLength(8)
        self.lineEditPort.setObjectName("lineEditPort")
        self.gridLayout.addWidget(self.lineEditPort, 0, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 4, 1, 1)
        self.lineEditNickName = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditNickName.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditNickName.setText("")
        self.lineEditNickName.setMaxLength(20)
        self.lineEditNickName.setObjectName("lineEditNickName")
        self.gridLayout.addWidget(self.lineEditNickName, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditHost = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditHost.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEditHost.setMaxLength(15)
        self.lineEditHost.setObjectName("lineEditHost")
        self.gridLayout.addWidget(self.lineEditHost, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(30, 80, 81, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.listWidgetRequests = QtWidgets.QListWidget(self.tab_2)
        self.listWidgetRequests.setGeometry(QtCore.QRect(11, 105, 119, 295))
        self.listWidgetRequests.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.listWidgetRequests.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidgetRequests.setObjectName("listWidgetRequests")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidgetKeys = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidgetKeys.setGeometry(QtCore.QRect(10, 10, 600, 391))
        self.tabWidgetKeys.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidgetKeys.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidgetKeys.setObjectName("tabWidgetKeys")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 50, 551, 331))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 0, 0, 1, 1)
        self.textEditMyPrivatKeyRSA = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEditMyPrivatKeyRSA.setMaximumSize(QtCore.QSize(16777215, 130))
        self.textEditMyPrivatKeyRSA.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditMyPrivatKeyRSA.setObjectName("textEditMyPrivatKeyRSA")
        self.gridLayout_6.addWidget(self.textEditMyPrivatKeyRSA, 3, 0, 1, 1)
        self.textEditMyPublicKeyRSA = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEditMyPublicKeyRSA.setMaximumSize(QtCore.QSize(16777215, 130))
        self.textEditMyPublicKeyRSA.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditMyPublicKeyRSA.setObjectName("textEditMyPublicKeyRSA")
        self.gridLayout_6.addWidget(self.textEditMyPublicKeyRSA, 1, 0, 1, 1)
        self.groupBoxGenKeysRSA = QtWidgets.QGroupBox(self.tab_5)
        self.groupBoxGenKeysRSA.setEnabled(True)
        self.groupBoxGenKeysRSA.setGeometry(QtCore.QRect(10, -10, 550, 60))
        self.groupBoxGenKeysRSA.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBoxGenKeysRSA.setTitle("")
        self.groupBoxGenKeysRSA.setFlat(False)
        self.groupBoxGenKeysRSA.setObjectName("groupBoxGenKeysRSA")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBoxGenKeysRSA)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 20, 521, 36))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayoutGenKeysRSA = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayoutGenKeysRSA.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutGenKeysRSA.setObjectName("gridLayoutGenKeysRSA")
        self.comboBoxBitRSA = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBoxBitRSA.setMaximumSize(QtCore.QSize(70, 16777215))
        self.comboBoxBitRSA.setEditable(False)
        self.comboBoxBitRSA.setMaxVisibleItems(10)
        self.comboBoxBitRSA.setMaxCount(10)
        self.comboBoxBitRSA.setMinimumContentsLength(0)
        self.comboBoxBitRSA.setDuplicatesEnabled(False)
        self.comboBoxBitRSA.setObjectName("comboBoxBitRSA")
        self.comboBoxBitRSA.addItem("")
        self.comboBoxBitRSA.addItem("")
        self.gridLayoutGenKeysRSA.addWidget(self.comboBoxBitRSA, 0, 2, 1, 1)
        self.pushButtonGenNewKeysRSA = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButtonGenNewKeysRSA.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButtonGenNewKeysRSA.setObjectName("pushButtonGenNewKeysRSA")
        self.gridLayoutGenKeysRSA.addWidget(self.pushButtonGenNewKeysRSA, 0, 0, 1, 1)
        self.labelBitRSA = QtWidgets.QLabel(self.layoutWidget2)
        self.labelBitRSA.setMaximumSize(QtCore.QSize(40, 15))
        self.labelBitRSA.setObjectName("labelBitRSA")
        self.gridLayoutGenKeysRSA.addWidget(self.labelBitRSA, 0, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_14.setObjectName("label_14")
        self.gridLayoutGenKeysRSA.addWidget(self.label_14, 0, 1, 1, 1)
        self.tabWidgetKeys.addTab(self.tab_5, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.textEditKeyRoomAES = QtWidgets.QTextEdit(self.tab_8)
        self.textEditKeyRoomAES.setGeometry(QtCore.QRect(10, 40, 550, 41))
        self.textEditKeyRoomAES.setMaximumSize(QtCore.QSize(16777215, 70))
        self.textEditKeyRoomAES.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditKeyRoomAES.setObjectName("textEditKeyRoomAES")
        self.label_18 = QtWidgets.QLabel(self.tab_8)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 549, 15))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_18.setObjectName("label_18")
        self.pushButtonGenAES = QtWidgets.QPushButton(self.tab_8)
        self.pushButtonGenAES.setGeometry(QtCore.QRect(390, 90, 161, 25))
        self.pushButtonGenAES.setObjectName("pushButtonGenAES")
        self.tabWidgetKeys.addTab(self.tab_8, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.textEditPublicKeyServer = QtWidgets.QTextEdit(self.tab_6)
        self.textEditPublicKeyServer.setGeometry(QtCore.QRect(10, 30, 550, 151))
        self.textEditPublicKeyServer.setMaximumSize(QtCore.QSize(16777215, 200))
        self.textEditPublicKeyServer.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditPublicKeyServer.setObjectName("textEditPublicKeyServer")
        self.label_12 = QtWidgets.QLabel(self.tab_6)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 549, 15))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_12.setObjectName("label_12")
        self.tabWidgetKeys.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.textEditPublicKeysClients = QtWidgets.QTextEdit(self.tab_7)
        self.textEditPublicKeysClients.setGeometry(QtCore.QRect(10, 30, 550, 351))
        self.textEditPublicKeysClients.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEditPublicKeysClients.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditPublicKeysClients.setObjectName("textEditPublicKeysClients")
        self.label_19 = QtWidgets.QLabel(self.tab_7)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 549, 15))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_19.setObjectName("label_19")
        self.tabWidgetKeys.addTab(self.tab_7, "")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textEditRandomNumber = QtWidgets.QTextEdit(self.tab_4)
        self.textEditRandomNumber.setGeometry(QtCore.QRect(10, 320, 600, 81))
        self.textEditRandomNumber.setMinimumSize(QtCore.QSize(0, 81))
        self.textEditRandomNumber.setMaximumSize(QtCore.QSize(16777215, 81))
        self.textEditRandomNumber.setObjectName("textEditRandomNumber")
        self.frame = QtWidgets.QFrame(self.tab_4)
        self.frame.setGeometry(QtCore.QRect(10, 50, 600, 261))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(10, 10, 580, 241))
        self.widget.setBaseSize(QtCore.QSize(0, 0))
        self.widget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.widget.setMouseTracking(False)
        self.widget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.widget.setAutoFillBackground(False)
        self.widget.setObjectName("widget")
        self.labelPlaceForArt = QtWidgets.QLabel(self.widget)
        self.labelPlaceForArt.setEnabled(False)
        self.labelPlaceForArt.setGeometry(QtCore.QRect(0, 0, 580, 241))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.labelPlaceForArt.setFont(font)
        self.labelPlaceForArt.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelPlaceForArt.setMouseTracking(False)
        self.labelPlaceForArt.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.labelPlaceForArt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelPlaceForArt.setAutoFillBackground(False)
        self.labelPlaceForArt.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPlaceForArt.setObjectName("labelPlaceForArt")
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 601, 36))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widgetColor = QtWidgets.QWidget(self.layoutWidget3)
        self.widgetColor.setMinimumSize(QtCore.QSize(230, 30))
        self.widgetColor.setMaximumSize(QtCore.QSize(230, 30))
        self.widgetColor.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.widgetColor.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));")
        self.widgetColor.setObjectName("widgetColor")
        self.horizontalLayout.addWidget(self.widgetColor)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout.addWidget(self.label_20)
        self.horizontalSliderSizePoint = QtWidgets.QSlider(self.layoutWidget3)
        self.horizontalSliderSizePoint.setMinimum(1)
        self.horizontalSliderSizePoint.setMaximum(50)
        self.horizontalSliderSizePoint.setProperty("value", 10)
        self.horizontalSliderSizePoint.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderSizePoint.setInvertedAppearance(False)
        self.horizontalSliderSizePoint.setInvertedControls(False)
        self.horizontalSliderSizePoint.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSliderSizePoint.setTickInterval(5)
        self.horizontalSliderSizePoint.setObjectName("horizontalSliderSizePoint")
        self.horizontalLayout.addWidget(self.horizontalSliderSizePoint)
        self.pushButtonClearPoints = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButtonClearPoints.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButtonClearPoints.setObjectName("pushButtonClearPoints")
        self.horizontalLayout.addWidget(self.pushButtonClearPoints)
        self.tabWidget.addTab(self.tab_4, "")
        self.layoutWidget4 = QtWidgets.QWidget(formrsachat)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 10, 251, 36))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButtonConnect = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.gridLayout_4.addWidget(self.pushButtonConnect, 0, 0, 1, 1)
        self.pushButtonDisconnect = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButtonDisconnect.setEnabled(False)
        self.pushButtonDisconnect.setObjectName("pushButtonDisconnect")
        self.gridLayout_4.addWidget(self.pushButtonDisconnect, 0, 1, 1, 1)
        self.labelYourID = QtWidgets.QLabel(formrsachat)
        self.labelYourID.setGeometry(QtCore.QRect(10, 485, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Kufi Arabic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelYourID.setFont(font)
        self.labelYourID.setObjectName("labelYourID")

        self.retranslateUi(formrsachat)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidgetKeys.setCurrentIndex(0)
        self.comboBoxBitRSA.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(formrsachat)

    def retranslateUi(self, formrsachat):
        _translate = QtCore.QCoreApplication.translate
        formrsachat.setWindowTitle(_translate("formrsachat", "rsachat"))
        self.pushButtonCreateRoom.setText(_translate("formrsachat", "Create Room"))
        self.labelOnline.setText(_translate("formrsachat", "Online:"))
        self.labelNameRoom.setText(_translate("formrsachat", "<html><head/><body><p align=\"center\">-</p></body></html>"))
        self.pushButtonSendMsg.setText(_translate("formrsachat", "Send"))
        self.textEditGlobal.setHtml(_translate("formrsachat", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButtonExitRoom.setText(_translate("formrsachat", "Exit Room"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("formrsachat", "Chat"))
        self.label_2.setText(_translate("formrsachat", "Port:"))
        self.lineEditPort.setText(_translate("formrsachat", "8000"))
        self.label_8.setText(_translate("formrsachat", "Nick Name:"))
        self.label.setText(_translate("formrsachat", "IP:"))
        self.lineEditHost.setText(_translate("formrsachat", "127.0.0.1"))
        self.label_4.setText(_translate("formrsachat", "Requests:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("formrsachat", "Setting"))
        self.label_10.setText(_translate("formrsachat", "My Privat Key"))
        self.label_9.setText(_translate("formrsachat", "My Public Key"))
        self.comboBoxBitRSA.setItemText(0, _translate("formrsachat", "4096"))
        self.comboBoxBitRSA.setItemText(1, _translate("formrsachat", "2048"))
        self.pushButtonGenNewKeysRSA.setText(_translate("formrsachat", "Gen new keys"))
        self.labelBitRSA.setText(_translate("formrsachat", "Bit"))
        self.label_14.setText(_translate("formrsachat", "Cryptographic stength"))
        self.tabWidgetKeys.setTabText(self.tabWidgetKeys.indexOf(self.tab_5), _translate("formrsachat", "My keys"))
        self.label_18.setText(_translate("formrsachat", "Key Room ( AES-256 )"))
        self.pushButtonGenAES.setText(_translate("formrsachat", "Gen new AES-256 keys"))
        self.tabWidgetKeys.setTabText(self.tabWidgetKeys.indexOf(self.tab_8), _translate("formrsachat", "Key Room"))
        self.label_12.setText(_translate("formrsachat", "Public Key server\'s"))
        self.tabWidgetKeys.setTabText(self.tabWidgetKeys.indexOf(self.tab_6), _translate("formrsachat", "Server Keys"))
        self.label_19.setText(_translate("formrsachat", "Public Keys Clients"))
        self.tabWidgetKeys.setTabText(self.tabWidgetKeys.indexOf(self.tab_7), _translate("formrsachat", "Clients keys"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("formrsachat", "Keys"))
        self.labelPlaceForArt.setText(_translate("formrsachat", "place for art"))
        self.widgetColor.setToolTip(_translate("formrsachat", "<html><head/><body><p><br/></p></body></html>"))
        self.widgetColor.setWhatsThis(_translate("formrsachat", "<html><head/><body><p><br/></p></body></html>"))
        self.label_20.setText(_translate("formrsachat", "size point:"))
        self.pushButtonClearPoints.setText(_translate("formrsachat", "Clear All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("formrsachat", "Gen Random"))
        self.pushButtonConnect.setText(_translate("formrsachat", "Connect to server"))
        self.pushButtonDisconnect.setText(_translate("formrsachat", "Disconnect"))
        self.labelYourID.setText(_translate("formrsachat", "your id:"))

