# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(635, 511)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 611, 441))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 13, 591, 391))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonCreateRoom = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonCreateRoom.setEnabled(False)
        self.pushButtonCreateRoom.setMinimumSize(QtCore.QSize(123, 0))
        self.pushButtonCreateRoom.setMaximumSize(QtCore.QSize(123, 20))
        self.pushButtonCreateRoom.setObjectName("pushButtonCreateRoom")
        self.gridLayout_2.addWidget(self.pushButtonCreateRoom, 3, 3, 1, 1)
        self.lineEditSendMsg = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.lineEditSendMsg.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lineEditSendMsg.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lineEditSendMsg.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lineEditSendMsg.setObjectName("lineEditSendMsg")
        self.gridLayout_2.addWidget(self.lineEditSendMsg, 6, 0, 2, 3)
        self.pushButtonExitRoom = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonExitRoom.setEnabled(False)
        self.pushButtonExitRoom.setMinimumSize(QtCore.QSize(123, 0))
        self.pushButtonExitRoom.setMaximumSize(QtCore.QSize(123, 20))
        self.pushButtonExitRoom.setObjectName("pushButtonExitRoom")
        self.gridLayout_2.addWidget(self.pushButtonExitRoom, 4, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.labelNameRoom = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelNameRoom.setFont(font)
        self.labelNameRoom.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.labelNameRoom.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelNameRoom.setTextFormat(QtCore.Qt.AutoText)
        self.labelNameRoom.setObjectName("labelNameRoom")
        self.gridLayout_2.addWidget(self.labelNameRoom, 0, 1, 1, 2)
        self.textEdit_Global = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit_Global.setMinimumSize(QtCore.QSize(460, 0))
        self.textEdit_Global.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.textEdit_Global.setObjectName("textEdit_Global")
        self.gridLayout_2.addWidget(self.textEdit_Global, 1, 0, 5, 3)
        self.listWidgetRooms = QtWidgets.QListWidget(self.layoutWidget)
        self.listWidgetRooms.setMinimumSize(QtCore.QSize(123, 0))
        self.listWidgetRooms.setMaximumSize(QtCore.QSize(123, 16777215))
        self.listWidgetRooms.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.listWidgetRooms.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidgetRooms.setObjectName("listWidgetRooms")
        self.gridLayout_2.addWidget(self.listWidgetRooms, 1, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAutoFillBackground(False)
        self.label_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEditNameNewRoom = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditNameNewRoom.setEnabled(False)
        self.lineEditNameNewRoom.setMinimumSize(QtCore.QSize(123, 0))
        self.lineEditNameNewRoom.setMaximumSize(QtCore.QSize(123, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEditNameNewRoom.setFont(font)
        self.lineEditNameNewRoom.setMaxLength(30)
        self.lineEditNameNewRoom.setObjectName("lineEditNameNewRoom")
        self.gridLayout_2.addWidget(self.lineEditNameNewRoom, 2, 3, 1, 1)
        self.pushButtonSendMsg = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonSendMsg.setEnabled(False)
        self.pushButtonSendMsg.setMinimumSize(QtCore.QSize(123, 0))
        self.pushButtonSendMsg.setMaximumSize(QtCore.QSize(123, 16777215))
        self.pushButtonSendMsg.setObjectName("pushButtonSendMsg")
        self.gridLayout_2.addWidget(self.pushButtonSendMsg, 7, 3, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBoxHostPortNick = QtWidgets.QGroupBox(self.tab_2)
        self.groupBoxHostPortNick.setEnabled(True)
        self.groupBoxHostPortNick.setGeometry(QtCore.QRect(10, 0, 581, 60))
        self.groupBoxHostPortNick.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBoxHostPortNick.setTitle("")
        self.groupBoxHostPortNick.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxHostPortNick.setFlat(False)
        self.groupBoxHostPortNick.setCheckable(False)
        self.groupBoxHostPortNick.setObjectName("groupBoxHostPortNick")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBoxHostPortNick)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 20, 561, 34))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setLineWidth(1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.lineEditPort = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditPort.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEditPort.setMaxLength(8)
        self.lineEditPort.setObjectName("lineEditPort")
        self.gridLayout.addWidget(self.lineEditPort, 0, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 4, 1, 1)
        self.lineEditNickName = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditNickName.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditNickName.setText("")
        self.lineEditNickName.setMaxLength(20)
        self.lineEditNickName.setObjectName("lineEditNickName")
        self.gridLayout.addWidget(self.lineEditNickName, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditHost = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditHost.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEditHost.setMaxLength(15)
        self.lineEditHost.setObjectName("lineEditHost")
        self.gridLayout.addWidget(self.lineEditHost, 0, 1, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 80, 101, 321))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.listWidgetRequests = QtWidgets.QListWidget(self.layoutWidget2)
        self.listWidgetRequests.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.listWidgetRequests.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidgetRequests.setObjectName("listWidgetRequests")
        self.verticalLayout.addWidget(self.listWidgetRequests)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 10, 591, 411))
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 50, 541, 331))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 0, 0, 1, 1)
        self.textEditMyPrivatKeyRSA = QtWidgets.QTextEdit(self.layoutWidget3)
        self.textEditMyPrivatKeyRSA.setMaximumSize(QtCore.QSize(16777215, 130))
        self.textEditMyPrivatKeyRSA.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditMyPrivatKeyRSA.setObjectName("textEditMyPrivatKeyRSA")
        self.gridLayout_6.addWidget(self.textEditMyPrivatKeyRSA, 3, 0, 1, 1)
        self.textEditMyPublicKeyRSA = QtWidgets.QTextEdit(self.layoutWidget3)
        self.textEditMyPublicKeyRSA.setMaximumSize(QtCore.QSize(16777215, 130))
        self.textEditMyPublicKeyRSA.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditMyPublicKeyRSA.setObjectName("textEditMyPublicKeyRSA")
        self.gridLayout_6.addWidget(self.textEditMyPublicKeyRSA, 1, 0, 1, 1)
        self.groupBoxGenKeysRSA = QtWidgets.QGroupBox(self.tab_5)
        self.groupBoxGenKeysRSA.setEnabled(True)
        self.groupBoxGenKeysRSA.setGeometry(QtCore.QRect(10, -10, 541, 60))
        self.groupBoxGenKeysRSA.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBoxGenKeysRSA.setTitle("")
        self.groupBoxGenKeysRSA.setFlat(False)
        self.groupBoxGenKeysRSA.setObjectName("groupBoxGenKeysRSA")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBoxGenKeysRSA)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 20, 521, 36))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayoutGenKeysRSA = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayoutGenKeysRSA.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutGenKeysRSA.setObjectName("gridLayoutGenKeysRSA")
        self.comboBoxBitRSA = QtWidgets.QComboBox(self.layoutWidget4)
        self.comboBoxBitRSA.setMaximumSize(QtCore.QSize(70, 16777215))
        self.comboBoxBitRSA.setEditable(False)
        self.comboBoxBitRSA.setMaxVisibleItems(10)
        self.comboBoxBitRSA.setMaxCount(10)
        self.comboBoxBitRSA.setMinimumContentsLength(0)
        self.comboBoxBitRSA.setDuplicatesEnabled(False)
        self.comboBoxBitRSA.setObjectName("comboBoxBitRSA")
        self.comboBoxBitRSA.addItem("")
        self.comboBoxBitRSA.addItem("")
        self.gridLayoutGenKeysRSA.addWidget(self.comboBoxBitRSA, 0, 2, 1, 1)
        self.pushButtonGenNewKeysRSA = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButtonGenNewKeysRSA.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButtonGenNewKeysRSA.setObjectName("pushButtonGenNewKeysRSA")
        self.gridLayoutGenKeysRSA.addWidget(self.pushButtonGenNewKeysRSA, 0, 0, 1, 1)
        self.labelBitRSA = QtWidgets.QLabel(self.layoutWidget4)
        self.labelBitRSA.setMaximumSize(QtCore.QSize(40, 15))
        self.labelBitRSA.setObjectName("labelBitRSA")
        self.gridLayoutGenKeysRSA.addWidget(self.labelBitRSA, 0, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_14.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_14.setObjectName("label_14")
        self.gridLayoutGenKeysRSA.addWidget(self.label_14, 0, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.textEditKeyRoomAES = QtWidgets.QTextEdit(self.tab_8)
        self.textEditKeyRoomAES.setGeometry(QtCore.QRect(10, 40, 541, 41))
        self.textEditKeyRoomAES.setMaximumSize(QtCore.QSize(16777215, 70))
        self.textEditKeyRoomAES.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditKeyRoomAES.setObjectName("textEditKeyRoomAES")
        self.label_18 = QtWidgets.QLabel(self.tab_8)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 549, 15))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_18.setObjectName("label_18")
        self.pushButtonGenAES = QtWidgets.QPushButton(self.tab_8)
        self.pushButtonGenAES.setGeometry(QtCore.QRect(390, 90, 161, 25))
        self.pushButtonGenAES.setObjectName("pushButtonGenAES")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.textEditPublicKeyServer = QtWidgets.QTextEdit(self.tab_6)
        self.textEditPublicKeyServer.setGeometry(QtCore.QRect(10, 30, 541, 151))
        self.textEditPublicKeyServer.setMaximumSize(QtCore.QSize(16777215, 200))
        self.textEditPublicKeyServer.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditPublicKeyServer.setObjectName("textEditPublicKeyServer")
        self.label_12 = QtWidgets.QLabel(self.tab_6)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 549, 15))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_12.setObjectName("label_12")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.textEditPublicKeysClients = QtWidgets.QTextEdit(self.tab_7)
        self.textEditPublicKeysClients.setGeometry(QtCore.QRect(10, 30, 541, 351))
        self.textEditPublicKeysClients.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEditPublicKeysClients.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditPublicKeysClients.setObjectName("textEditPublicKeysClients")
        self.label_19 = QtWidgets.QLabel(self.tab_7)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 549, 15))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_19.setObjectName("label_19")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textEditRandomNumber = QtWidgets.QTextEdit(self.tab_4)
        self.textEditRandomNumber.setGeometry(QtCore.QRect(10, 320, 581, 81))
        self.textEditRandomNumber.setObjectName("textEditRandomNumber")
        self.frame = QtWidgets.QFrame(self.tab_4)
        self.frame.setGeometry(QtCore.QRect(10, 50, 581, 261))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(10, 10, 561, 241))
        self.widget.setBaseSize(QtCore.QSize(0, 0))
        self.widget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.widget.setMouseTracking(False)
        self.widget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.widget.setAutoFillBackground(False)
        self.widget.setObjectName("widget")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 541, 221))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_5.setMouseTracking(False)
        self.label_5.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.layoutWidget5 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 10, 581, 36))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widgetColor = QtWidgets.QWidget(self.layoutWidget5)
        self.widgetColor.setMinimumSize(QtCore.QSize(230, 30))
        self.widgetColor.setMaximumSize(QtCore.QSize(230, 30))
        self.widgetColor.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.widgetColor.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));")
        self.widgetColor.setObjectName("widgetColor")
        self.horizontalLayout.addWidget(self.widgetColor)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout.addWidget(self.label_20)
        self.horizontalSliderSizePoint = QtWidgets.QSlider(self.layoutWidget5)
        self.horizontalSliderSizePoint.setMinimum(1)
        self.horizontalSliderSizePoint.setMaximum(50)
        self.horizontalSliderSizePoint.setProperty("value", 10)
        self.horizontalSliderSizePoint.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderSizePoint.setInvertedAppearance(False)
        self.horizontalSliderSizePoint.setInvertedControls(False)
        self.horizontalSliderSizePoint.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSliderSizePoint.setTickInterval(5)
        self.horizontalSliderSizePoint.setObjectName("horizontalSliderSizePoint")
        self.horizontalLayout.addWidget(self.horizontalSliderSizePoint)
        self.pushButtonClearPoints = QtWidgets.QPushButton(self.layoutWidget5)
        self.pushButtonClearPoints.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButtonClearPoints.setObjectName("pushButtonClearPoints")
        self.horizontalLayout.addWidget(self.pushButtonClearPoints)
        self.tabWidget.addTab(self.tab_4, "")
        self.layoutWidget6 = QtWidgets.QWidget(Form)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 10, 251, 36))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget6)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButtonConnect = QtWidgets.QPushButton(self.layoutWidget6)
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.gridLayout_4.addWidget(self.pushButtonConnect, 0, 0, 1, 1)
        self.pushButtonDisconnect = QtWidgets.QPushButton(self.layoutWidget6)
        self.pushButtonDisconnect.setEnabled(False)
        self.pushButtonDisconnect.setObjectName("pushButtonDisconnect")
        self.gridLayout_4.addWidget(self.pushButtonDisconnect, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 490, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.comboBoxBitRSA.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FBBL"))
        self.pushButtonCreateRoom.setText(_translate("Form", "Create Room"))
        self.pushButtonExitRoom.setText(_translate("Form", "Exit Room"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"right\">Name Room:</p></body></html>"))
        self.labelNameRoom.setText(_translate("Form", "<html><head/><body><p align=\"center\">-</p></body></html>"))
        self.label_11.setText(_translate("Form", "Online:"))
        self.pushButtonSendMsg.setText(_translate("Form", "Send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Chat"))
        self.label_2.setText(_translate("Form", "Port:"))
        self.lineEditPort.setText(_translate("Form", "8000"))
        self.label_8.setText(_translate("Form", "Nick Name:"))
        self.label.setText(_translate("Form", "IP:"))
        self.lineEditHost.setText(_translate("Form", "127.0.0.1"))
        self.label_4.setText(_translate("Form", "Requests:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Setting"))
        self.label_10.setText(_translate("Form", "My Privat Key"))
        self.label_9.setText(_translate("Form", "My Public Key"))
        self.comboBoxBitRSA.setItemText(0, _translate("Form", "4096"))
        self.comboBoxBitRSA.setItemText(1, _translate("Form", "2048"))
        self.pushButtonGenNewKeysRSA.setText(_translate("Form", "Gen new keys"))
        self.labelBitRSA.setText(_translate("Form", "Bit"))
        self.label_14.setText(_translate("Form", "Cryptographic stength"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Form", "My keys"))
        self.label_18.setText(_translate("Form", "Key Room ( AES-256 )"))
        self.pushButtonGenAES.setText(_translate("Form", "Gen new AES-256 keys"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("Form", "Key Room"))
        self.label_12.setText(_translate("Form", "Public Key server\'s"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("Form", "Server Keys"))
        self.label_19.setText(_translate("Form", "Public Keys Clients"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("Form", "Clients keys"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Keys"))
        self.label_5.setText(_translate("Form", "place for art"))
        self.widgetColor.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.widgetColor.setWhatsThis(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.label_20.setText(_translate("Form", "size point:"))
        self.pushButtonClearPoints.setText(_translate("Form", "Clear All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Gen Random"))
        self.pushButtonConnect.setText(_translate("Form", "Connect to server"))
        self.pushButtonDisconnect.setText(_translate("Form", "Disconnect"))
        self.label_3.setText(_translate("Form", "your id:"))

