# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Forms/WidgetTemplateChat.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormTemplateChat(object):
    def setupUi(self, FormTemplateChat):
        FormTemplateChat.setObjectName("FormTemplateChat")
        FormTemplateChat.resize(503, 424)
        FormTemplateChat.setStyleSheet("")
        self.layoutWidget = QtWidgets.QWidget(FormTemplateChat)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 2, 501, 421))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonExitRoom = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonExitRoom.setMinimumSize(QtCore.QSize(80, 20))
        self.pushButtonExitRoom.setMaximumSize(QtCore.QSize(80, 20))
        self.pushButtonExitRoom.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButtonExitRoom.setAutoFillBackground(True)
        self.pushButtonExitRoom.setAutoDefault(False)
        self.pushButtonExitRoom.setDefault(False)
        self.pushButtonExitRoom.setFlat(True)
        self.pushButtonExitRoom.setObjectName("pushButtonExitRoom")
        self.gridLayout.addWidget(self.pushButtonExitRoom, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(5, 30, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 1)
        self.nameRoomLabel = QtWidgets.QLabel(self.layoutWidget)
        self.nameRoomLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.nameRoomLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.nameRoomLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.nameRoomLabel.setText("")
        self.nameRoomLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nameRoomLabel.setObjectName("nameRoomLabel")
        self.gridLayout.addWidget(self.nameRoomLabel, 0, 2, 1, 1)
        self.indicatorLabel = QtWidgets.QLabel(self.layoutWidget)
        self.indicatorLabel.setMinimumSize(QtCore.QSize(60, 20))
        self.indicatorLabel.setMaximumSize(QtCore.QSize(60, 20))
        self.indicatorLabel.setText("")
        self.indicatorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.indicatorLabel.setObjectName("indicatorLabel")
        self.gridLayout.addWidget(self.indicatorLabel, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(5, 30, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.pushButtonShowOnline = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonShowOnline.setMinimumSize(QtCore.QSize(30, 20))
        self.pushButtonShowOnline.setMaximumSize(QtCore.QSize(30, 20))
        self.pushButtonShowOnline.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButtonShowOnline.setAutoFillBackground(True)
        self.pushButtonShowOnline.setAutoDefault(False)
        self.pushButtonShowOnline.setDefault(False)
        self.pushButtonShowOnline.setFlat(True)
        self.pushButtonShowOnline.setObjectName("pushButtonShowOnline")
        self.gridLayout.addWidget(self.pushButtonShowOnline, 0, 5, 1, 1)
        self.splitter2 = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter2.setHandleWidth(1)
        self.splitter2.setChildrenCollapsible(False)
        self.splitter2.setObjectName("splitter2")
        self.splitter1 = QtWidgets.QSplitter(self.splitter2)
        self.splitter1.setOrientation(QtCore.Qt.Vertical)
        self.splitter1.setHandleWidth(1)
        self.splitter1.setChildrenCollapsible(False)
        self.splitter1.setObjectName("splitter1")
        self.textEditGlobal = QtWidgets.QTextEdit(self.splitter1)
        self.textEditGlobal.setMinimumSize(QtCore.QSize(0, 0))
        self.textEditGlobal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEditGlobal.setUndoRedoEnabled(True)
        self.textEditGlobal.setReadOnly(True)
        self.textEditGlobal.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEditGlobal.setObjectName("textEditGlobal")
        self.lineEditSendMsg = QtWidgets.QPlainTextEdit(self.splitter1)
        self.lineEditSendMsg.setMaximumSize(QtCore.QSize(16777215, 200))
        self.lineEditSendMsg.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lineEditSendMsg.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lineEditSendMsg.setObjectName("lineEditSendMsg")
        self.listWidgetOnline = QtWidgets.QListWidget(self.splitter2)
        self.listWidgetOnline.setMinimumSize(QtCore.QSize(80, 0))
        self.listWidgetOnline.setMaximumSize(QtCore.QSize(150, 16777215))
        self.listWidgetOnline.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.listWidgetOnline.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidgetOnline.setObjectName("listWidgetOnline")
        self.gridLayout.addWidget(self.splitter2, 1, 0, 1, 7)
        self.pushButtonSettings = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonSettings.setMinimumSize(QtCore.QSize(80, 20))
        self.pushButtonSettings.setMaximumSize(QtCore.QSize(80, 20))
        self.pushButtonSettings.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButtonSettings.setAutoFillBackground(True)
        self.pushButtonSettings.setAutoDefault(False)
        self.pushButtonSettings.setDefault(False)
        self.pushButtonSettings.setFlat(True)
        self.pushButtonSettings.setObjectName("pushButtonSettings")
        self.gridLayout.addWidget(self.pushButtonSettings, 0, 3, 1, 1)
        self.indicatorLabel.setBuddy(self.indicatorLabel)

        self.retranslateUi(FormTemplateChat)
        QtCore.QMetaObject.connectSlotsByName(FormTemplateChat)

    def retranslateUi(self, FormTemplateChat):
        _translate = QtCore.QCoreApplication.translate
        FormTemplateChat.setWindowTitle(_translate("FormTemplateChat", "FormTemplateChat"))
        self.pushButtonExitRoom.setText(_translate("FormTemplateChat", "Exit Room"))
        self.pushButtonShowOnline.setText(_translate("FormTemplateChat", ">"))
        self.textEditGlobal.setHtml(_translate("FormTemplateChat", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButtonSettings.setText(_translate("FormTemplateChat", "Settings"))

