# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Forms/WidgetMyKeys.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormMyKeys(object):
    def setupUi(self, FormMyKeys):
        FormMyKeys.setObjectName("FormMyKeys")
        FormMyKeys.resize(640, 711)
        FormMyKeys.setMinimumSize(QtCore.QSize(640, 480))
        self.layoutWidget = QtWidgets.QWidget(FormMyKeys)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 621, 36))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayoutGenKeysRSA = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayoutGenKeysRSA.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutGenKeysRSA.setObjectName("gridLayoutGenKeysRSA")
        self.comboBoxBitRSA = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxBitRSA.setMaximumSize(QtCore.QSize(70, 16777215))
        self.comboBoxBitRSA.setEditable(False)
        self.comboBoxBitRSA.setMaxVisibleItems(10)
        self.comboBoxBitRSA.setMaxCount(10)
        self.comboBoxBitRSA.setMinimumContentsLength(0)
        self.comboBoxBitRSA.setDuplicatesEnabled(False)
        self.comboBoxBitRSA.setObjectName("comboBoxBitRSA")
        self.comboBoxBitRSA.addItem("")
        self.comboBoxBitRSA.addItem("")
        self.gridLayoutGenKeysRSA.addWidget(self.comboBoxBitRSA, 0, 2, 1, 1)
        self.pushButtonGenNewKeysRSA = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonGenNewKeysRSA.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButtonGenNewKeysRSA.setObjectName("pushButtonGenNewKeysRSA")
        self.gridLayoutGenKeysRSA.addWidget(self.pushButtonGenNewKeysRSA, 0, 0, 1, 1)
        self.labelBitRSA = QtWidgets.QLabel(self.layoutWidget)
        self.labelBitRSA.setMaximumSize(QtCore.QSize(40, 15))
        self.labelBitRSA.setObjectName("labelBitRSA")
        self.gridLayoutGenKeysRSA.addWidget(self.labelBitRSA, 0, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_14.setObjectName("label_14")
        self.gridLayoutGenKeysRSA.addWidget(self.label_14, 0, 1, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(FormMyKeys)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 60, 621, 411))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 2, 0, 1, 1)
        self.textEditMyPrivatKeyRSA = QtWidgets.QTextEdit(self.layoutWidget_2)
        self.textEditMyPrivatKeyRSA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEditMyPrivatKeyRSA.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditMyPrivatKeyRSA.setObjectName("textEditMyPrivatKeyRSA")
        self.gridLayout_6.addWidget(self.textEditMyPrivatKeyRSA, 3, 0, 1, 1)
        self.textEditMyPublicKeyRSA = QtWidgets.QTextEdit(self.layoutWidget_2)
        self.textEditMyPublicKeyRSA.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEditMyPublicKeyRSA.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditMyPublicKeyRSA.setObjectName("textEditMyPublicKeyRSA")
        self.gridLayout_6.addWidget(self.textEditMyPublicKeyRSA, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(FormMyKeys)
        self.label_12.setGeometry(QtCore.QRect(10, 480, 549, 15))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_12.setObjectName("label_12")
        self.textEditPublicKeyServer = QtWidgets.QTextEdit(FormMyKeys)
        self.textEditPublicKeyServer.setGeometry(QtCore.QRect(10, 500, 621, 171))
        self.textEditPublicKeyServer.setMaximumSize(QtCore.QSize(16777215, 200))
        self.textEditPublicKeyServer.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditPublicKeyServer.setObjectName("textEditPublicKeyServer")
        self.pushButtonClose = QtWidgets.QPushButton(FormMyKeys)
        self.pushButtonClose.setGeometry(QtCore.QRect(540, 680, 91, 25))
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.pushButtonSave = QtWidgets.QPushButton(FormMyKeys)
        self.pushButtonSave.setGeometry(QtCore.QRect(440, 680, 91, 25))
        self.pushButtonSave.setObjectName("pushButtonSave")

        self.retranslateUi(FormMyKeys)
        self.comboBoxBitRSA.setCurrentIndex(1)
        self.pushButtonClose.clicked.connect(FormMyKeys.hide)
        QtCore.QMetaObject.connectSlotsByName(FormMyKeys)

    def retranslateUi(self, FormMyKeys):
        _translate = QtCore.QCoreApplication.translate
        FormMyKeys.setWindowTitle(_translate("FormMyKeys", "My Keys"))
        self.comboBoxBitRSA.setItemText(0, _translate("FormMyKeys", "4096"))
        self.comboBoxBitRSA.setItemText(1, _translate("FormMyKeys", "2048"))
        self.pushButtonGenNewKeysRSA.setText(_translate("FormMyKeys", "Gen new keys"))
        self.labelBitRSA.setText(_translate("FormMyKeys", "Bit"))
        self.label_14.setText(_translate("FormMyKeys", "Cryptographic stength"))
        self.label_10.setText(_translate("FormMyKeys", "My Privat Key"))
        self.label_9.setText(_translate("FormMyKeys", "My Public Key"))
        self.label_12.setText(_translate("FormMyKeys", "Public Key server\'s"))
        self.pushButtonClose.setText(_translate("FormMyKeys", "Close"))
        self.pushButtonSave.setText(_translate("FormMyKeys", "Save"))

